#!/usr/bin/env bash
# ::DESCRIPTION
# Launcher that downloads a versioned release artifact if no executable exists.
#
# ::OVERRIDES
# Usage: export <option>=<value>
# - MKB_VERSION: The release artifact version.
# - MKB_ARTIFACTS_URL: A templated URL in the format `https://example.com/<VERSION>/<FILE>`.
# - MKB_NO_VERIFY: Disable verifying the code signature of downloaded artifacts.

set -eu

readonly srcroot="$(dirname "$0")"
pushd . > /dev/null
cd "${srcroot}"

readonly binDir="bin"
readonly mockingbirdZip="./mockingbird.zip"
mkdir -p "${binDir}"
readonly executable="${binDir}/mockingbird/mockingbird"

# Extract
unzip -oq "${mockingbirdZip}" -d "${binDir}"
chmod u+x "${executable}"

popd > /dev/null
MKB_LAUNCHER="$0" "${executable}" "$@"
